/**
 * HTML Report Generator
 *
 * Generates interactive HTML reports with embedded CSS, responsive design,
 * and professional styling. No external dependencies required.
 *
 * @module htmlGenerator
 *
 * @example
 * ```typescript
 * import { generateHTML } from '@/report-generator/htmlGenerator';
 * import type { QAReport } from '@/types';
 *
 * const report: QAReport = { ... };
 * await generateHTML(report, './output/report.html');
 * ```
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { Issue, QAReport } from "@/types";
import { logger } from "@/utils/logger";

const log = logger.child({ component: "HTMLGenerator" });

/**
 * Generates an HTML report from a QAReport and saves it to the specified path.
 *
 * The output includes:
 * - Summary card with key metrics
 * - Scores visualization with progress bars
 * - Issues list with severity badges
 * - Actions timeline
 * - Screenshot gallery
 * - Embedded CSS for professional appearance
 * - Responsive design (mobile-friendly)
 * - Color coding: red (critical), orange (major), yellow (minor)
 *
 * @param report - Complete QA report to format
 * @param outputPath - Full path where HTML file will be saved
 * @throws Error if file write fails
 *
 * @example
 * ```typescript
 * await generateHTML(report, './output/report.html');
 * ```
 */
export async function generateHTML(
  report: QAReport,
  outputPath: string,
): Promise<void> {
  const startTime = Date.now();

  log.debug(
    {
      testId: report.meta.testId,
      outputPath,
    },
    "Generating HTML report",
  );

  try {
    const content = await buildHTMLContent(report, outputPath);

    // Write to file using Node.js fs API for cross-runtime compatibility
    await writeFile(outputPath, content, "utf-8");

    const duration = Date.now() - startTime;
    const sizeBytes = Buffer.byteLength(content, "utf-8");

    log.info(
      {
        testId: report.meta.testId,
        outputPath,
        duration,
        sizeBytes,
      },
      "Successfully generated HTML report",
    );
  } catch (error) {
    const err = error instanceof Error ? error : new Error(String(error));
    const duration = Date.now() - startTime;

    log.error(
      {
        error: err.message,
        testId: report.meta.testId,
        outputPath,
        duration,
      },
      "Failed to generate HTML report",
    );

    throw new Error(`Failed to generate HTML report: ${err.message}`);
  }
}

/**
 * Builds the complete HTML content from a QAReport.
 *
 * @param report - QA report to format
 * @param outputPath - Path where HTML will be saved (used to resolve screenshot paths)
 * @returns Complete HTML document string
 * @private
 */
async function buildHTMLContent(
  report: QAReport,
  outputPath: string,
): Promise<string> {
  const evidenceSection = await buildEvidenceSection(report, outputPath);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QA Report - ${escapeHtml(report.meta.gameUrl)}</title>
  <style>
    ${getEmbeddedCSS()}
  </style>
</head>
<body>
  <header>
    ${buildHeader(report)}
  </header>

  <main>
    ${buildSummaryCard(report)}
    ${buildBrowserSettingsSection(report)}
    ${buildScoresSection(report)}
    ${buildEvaluationSection(report)}
    ${buildIssuesSection(report)}
    ${buildActionsSection(report)}
    ${evidenceSection}
    ${report.progressMetrics ? buildProgressMetricsSection(report) : ""}
    ${report.timingMetrics ? buildTimingMetricsSection(report) : ""}
  </main>

  <footer>
    <p>Generated by Denethor Agent v${report.meta.agentVersion} on ${new Date(report.meta.timestamp).toLocaleString()}</p>
  </footer>

  <!-- Lightbox Modal -->
  <div id="lightbox" class="lightbox" onclick="closeLightbox()">
    <span class="lightbox-close">&times;</span>
    <img class="lightbox-content" id="lightbox-img" />
  </div>

  <script>
    function openLightbox(imageSrc) {
      document.getElementById('lightbox').style.display = 'block';
      document.getElementById('lightbox-img').src = imageSrc;
    }

    function closeLightbox() {
      document.getElementById('lightbox').style.display = 'none';
    }

    // Close on Escape key
    document.addEventListener('keydown', function(event) {
      if (event.key === 'Escape') {
        closeLightbox();
      }
    });
  </script>
</body>
</html>`;
}

/**
 * Returns embedded CSS for the HTML report.
 *
 * @returns CSS string
 * @private
 */
function getEmbeddedCSS(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }

    header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      margin-bottom: 30px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }

    header h1 {
      font-size: 28px;
      margin-bottom: 10px;
    }

    header .meta {
      font-size: 14px;
      opacity: 0.9;
    }

    main {
      max-width: 1200px;
      margin: 0 auto;
    }

    section {
      background: white;
      padding: 25px;
      margin-bottom: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    h2 {
      color: #667eea;
      margin-bottom: 20px;
      font-size: 22px;
      border-bottom: 2px solid #667eea;
      padding-bottom: 10px;
    }

    h3 {
      color: #764ba2;
      margin-top: 20px;
      margin-bottom: 10px;
      font-size: 18px;
    }

    .summary-card {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .summary-item {
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      text-align: center;
    }

    .summary-item .label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin-bottom: 10px;
    }

    .summary-item .value {
      font-size: 32px;
      font-weight: bold;
      color: #667eea;
    }

    .summary-item .status {
      display: inline-block;
      padding: 5px 15px;
      border-radius: 20px;
      font-size: 14px;
      font-weight: bold;
      margin-top: 10px;
    }

    .status.success {
      background: #10b981;
      color: white;
    }

    .status.failure {
      background: #ef4444;
      color: white;
    }

    .status.error {
      background: #f59e0b;
      color: white;
    }

    .settings-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-bottom: 20px;
    }

    .setting-item {
      background: #f9fafb;
      padding: 15px;
      border-radius: 6px;
      border-left: 3px solid #667eea;
    }

    .setting-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 8px;
      font-weight: 600;
    }

    .setting-value {
      font-size: 16px;
      color: #333;
      font-weight: 500;
    }

    .browser-arguments {
      background: #f9fafb;
      padding: 15px;
      border-radius: 6px;
      margin-top: 15px;
    }

    .arguments-list {
      list-style: none;
      margin-top: 10px;
    }

    .arguments-list li {
      padding: 6px 0;
    }

    .arguments-list code {
      background: #e5e7eb;
      padding: 4px 8px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
      font-size: 13px;
      color: #374151;
    }

    .score-bar {
      margin-bottom: 20px;
    }

    .score-bar .label {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
      font-weight: 500;
    }

    .score-bar .bar-container {
      width: 100%;
      height: 30px;
      background: #e5e7eb;
      border-radius: 15px;
      overflow: hidden;
      position: relative;
    }

    .score-bar .bar-fill {
      height: 100%;
      background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
      border-radius: 15px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      font-size: 14px;
      transition: width 0.3s ease;
    }

    .score-bar .bar-fill.excellent {
      background: linear-gradient(90deg, #10b981 0%, #059669 100%);
    }

    .score-bar .bar-fill.good {
      background: linear-gradient(90deg, #3b82f6 0%, #2563eb 100%);
    }

    .score-bar .bar-fill.fair {
      background: linear-gradient(90deg, #f59e0b 0%, #d97706 100%);
    }

    .score-bar .bar-fill.poor {
      background: linear-gradient(90deg, #ef4444 0%, #dc2626 100%);
    }

    .evaluation-box {
      background: #f9fafb;
      border-left: 4px solid #667eea;
      padding: 20px;
      border-radius: 4px;
      margin-bottom: 20px;
    }

    .confidence-badge {
      display: inline-block;
      background: #667eea;
      color: white;
      padding: 5px 12px;
      border-radius: 12px;
      font-size: 14px;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .issue-item {
      padding: 15px;
      margin-bottom: 15px;
      border-radius: 6px;
      border-left: 4px solid;
      background: #f9fafb;
    }

    .issue-item.critical {
      border-color: #ef4444;
      background: #fef2f2;
    }

    .issue-item.major {
      border-color: #f59e0b;
      background: #fffbeb;
    }

    .issue-item.minor {
      border-color: #10b981;
      background: #f0fdf4;
    }

    .issue-badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: bold;
      text-transform: uppercase;
      margin-right: 10px;
    }

    .issue-badge.critical {
      background: #ef4444;
      color: white;
    }

    .issue-badge.major {
      background: #f59e0b;
      color: white;
    }

    .issue-badge.minor {
      background: #10b981;
      color: white;
    }

    .action-timeline {
      list-style: none;
    }

    .action-item {
      padding: 12px 0;
      border-left: 2px solid #e5e7eb;
      padding-left: 20px;
      position: relative;
      margin-bottom: 10px;
    }

    .action-item::before {
      content: '';
      position: absolute;
      left: -6px;
      top: 16px;
      width: 10px;
      height: 10px;
      border-radius: 50%;
      background: #667eea;
    }

    .action-item.success::before {
      background: #10b981;
    }

    .action-item.failure::before {
      background: #ef4444;
    }

    .action-type {
      font-weight: bold;
      color: #667eea;
    }

    .action-timestamp {
      font-size: 12px;
      color: #666;
      margin-left: 10px;
    }

    .screenshot-gallery {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
      gap: 15px;
      margin-top: 20px;
    }

    .screenshot-item {
      background: #f9fafb;
      padding: 10px;
      border-radius: 6px;
      text-align: center;
      font-size: 12px;
      transition: transform 0.2s ease;
    }

    .screenshot-item:hover {
      transform: translateY(-4px);
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }

    .screenshot-item img {
      width: 100%;
      height: auto;
      border-radius: 4px;
      cursor: pointer;
      border: 2px solid #e5e7eb;
      margin-bottom: 8px;
    }

    .screenshot-item img:hover {
      border-color: #667eea;
    }

    .screenshot-item .filename {
      color: #666;
      word-break: break-all;
      font-family: monospace;
      font-size: 11px;
    }

    /* Lightbox Modal */
    .lightbox {
      display: none;
      position: fixed;
      z-index: 999;
      padding: 50px;
      left: 0;
      top: 0;
      width: 100%;
      height: 100%;
      overflow: auto;
      background-color: rgba(0,0,0,0.9);
    }

    .lightbox-content {
      margin: auto;
      display: block;
      max-width: 90%;
      max-height: 90%;
    }

    .lightbox-close {
      position: absolute;
      top: 15px;
      right: 35px;
      color: #f1f1f1;
      font-size: 40px;
      font-weight: bold;
      cursor: pointer;
    }

    .lightbox-close:hover {
      color: #bbb;
    }

    .log-path {
      background: #f9fafb;
      padding: 10px 15px;
      border-radius: 4px;
      margin-bottom: 10px;
      font-family: 'Courier New', monospace;
      font-size: 13px;
      color: #333;
      border: 1px solid #e5e7eb;
    }

    footer {
      text-align: center;
      padding: 20px;
      color: #666;
      font-size: 14px;
      margin-top: 30px;
    }

    @media (max-width: 768px) {
      body {
        padding: 10px;
      }

      header {
        padding: 20px;
      }

      header h1 {
        font-size: 22px;
      }

      section {
        padding: 15px;
      }

      .summary-card {
        grid-template-columns: 1fr;
      }

      .screenshot-gallery {
        grid-template-columns: 1fr;
      }

      .metrics-grid {
        grid-template-columns: 1fr;
      }
    }

    /* Metrics Grid Styles */
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin-top: 15px;
    }

    .metric-item {
      background: #f9fafb;
      padding: 15px;
      border-radius: 6px;
      border-left: 3px solid #667eea;
      text-align: center;
    }

    .metric-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 8px;
      font-weight: 600;
    }

    .metric-value {
      font-size: 24px;
      color: #667eea;
      font-weight: bold;
    }
  `;
}

/**
 * Builds the header section.
 *
 * @param report - QA report
 * @returns HTML header
 * @private
 */
function buildHeader(report: QAReport): string {
  return `
    <h1>QA Test Report</h1>
    <div class="meta">
      <strong>Test ID:</strong> ${escapeHtml(report.meta.testId)} &nbsp;|&nbsp;
      <strong>Game URL:</strong> <a href="${escapeHtml(report.meta.gameUrl)}" target="_blank" style="color: white; text-decoration: underline;">${escapeHtml(report.meta.gameUrl)}</a>
    </div>
  `;
}

/**
 * Builds the summary card section.
 *
 * @param report - QA report
 * @returns HTML summary card
 * @private
 */
function buildSummaryCard(report: QAReport): string {
  const durationMinutes = Math.floor(report.meta.duration / 60);
  const durationSeconds = report.meta.duration % 60;

  return `
    <div class="summary-card">
      <div class="summary-item">
        <div class="label">Status</div>
        <div class="status ${report.status}">${report.status.toUpperCase()}</div>
      </div>
      <div class="summary-item">
        <div class="label">Overall Score</div>
        <div class="value">${report.scores.overallPlayability}</div>
        <div style="font-size: 14px; color: #666;">out of 100</div>
      </div>
      <div class="summary-item">
        <div class="label">Duration</div>
        <div class="value">${durationMinutes}m ${durationSeconds}s</div>
      </div>
      <div class="summary-item">
        <div class="label">Issues Found</div>
        <div class="value">${report.issues.length}</div>
      </div>
    </div>
  `;
}

/**
 * Builds the browser settings section.
 *
 * @param report - QA report
 * @returns HTML browser settings section
 * @private
 */
function buildBrowserSettingsSection(report: QAReport): string {
  const settings = report.meta.browserSettings;

  return `
    <section class="browser-settings">
      <h2>Browser Configuration</h2>
      <div class="settings-grid">
        <div class="setting-item">
          <div class="setting-label">Browser</div>
          <div class="setting-value">${escapeHtml(settings.browser)}</div>
        </div>
        <div class="setting-item">
          <div class="setting-label">Device</div>
          <div class="setting-value">${escapeHtml(settings.device)}</div>
        </div>
        <div class="setting-item">
          <div class="setting-label">Viewport</div>
          <div class="setting-value">${settings.viewport.width} × ${settings.viewport.height}</div>
        </div>
        <div class="setting-item">
          <div class="setting-label">Locale</div>
          <div class="setting-value">${escapeHtml(settings.locale)}</div>
        </div>
      </div>
      ${
        settings.arguments.length > 0
          ? `
      <div class="browser-arguments">
        <div class="setting-label">Browser Arguments</div>
        <ul class="arguments-list">
          ${settings.arguments
            .map((arg) => `<li><code>${escapeHtml(arg)}</code></li>`)
            .join("")}
        </ul>
      </div>
      `
          : ""
      }
    </section>
  `;
}

/**
 * Builds the scores section with progress bars.
 *
 * @param report - QA report
 * @returns HTML scores section
 * @private
 */
function buildScoresSection(report: QAReport): string {
  return `
    <section class="scores">
      <h2>Playability Scores</h2>
      ${buildScoreBar("Load Success", report.scores.loadSuccess)}
      ${buildScoreBar("Responsiveness", report.scores.responsiveness)}
      ${buildScoreBar("Stability", report.scores.stability)}
      ${buildScoreBar("Overall Playability", report.scores.overallPlayability)}
    </section>
  `;
}

/**
 * Builds a single score bar.
 *
 * @param label - Score label
 * @param score - Score value (0-100)
 * @returns HTML score bar
 * @private
 */
function buildScoreBar(label: string, score: number): string {
  const status = getScoreClass(score);
  return `
    <div class="score-bar">
      <div class="label">
        <span>${label}</span>
        <span>${score}/100</span>
      </div>
      <div class="bar-container">
        <div class="bar-fill ${status}" style="width: ${score}%">
          ${score >= 20 ? `${score}%` : ""}
        </div>
      </div>
    </div>
  `;
}

/**
 * Gets CSS class based on score.
 *
 * @param score - Score value (0-100)
 * @returns CSS class name
 * @private
 */
function getScoreClass(score: number): string {
  if (score >= 90) return "excellent";
  if (score >= 70) return "good";
  if (score >= 40) return "fair";
  return "poor";
}

/**
 * Builds the evaluation section.
 *
 * @param report - QA report
 * @returns HTML evaluation section
 * @private
 */
function buildEvaluationSection(report: QAReport): string {
  return `
    <section class="evaluation">
      <h2>Evaluation</h2>
      <div class="evaluation-box">
        <span class="confidence-badge">Confidence: ${report.evaluation.confidence}%</span>
        <p style="margin-top: 15px;">${escapeHtml(report.evaluation.reasoning)}</p>
      </div>
    </section>
  `;
}

/**
 * Builds the issues section.
 *
 * @param report - QA report
 * @returns HTML issues section
 * @private
 */
function buildIssuesSection(report: QAReport): string {
  if (report.issues.length === 0) {
    return `
      <section class="issues">
        <h2>Issues</h2>
        <p style="color: #10b981; font-weight: bold;">No issues detected.</p>
      </section>
    `;
  }

  // Group by severity
  const critical = report.issues.filter((i) => i.severity === "critical");
  const major = report.issues.filter((i) => i.severity === "major");
  const minor = report.issues.filter((i) => i.severity === "minor");

  let issuesHTML = '<section class="issues"><h2>Issues</h2>';

  if (critical.length > 0) {
    issuesHTML += "<h3>Critical Issues</h3>";
    issuesHTML += critical.map((i) => buildIssueItem(i)).join("");
  }

  if (major.length > 0) {
    issuesHTML += "<h3>Major Issues</h3>";
    issuesHTML += major.map((i) => buildIssueItem(i)).join("");
  }

  if (minor.length > 0) {
    issuesHTML += "<h3>Minor Issues</h3>";
    issuesHTML += minor.map((i) => buildIssueItem(i)).join("");
  }

  issuesHTML += "</section>";
  return issuesHTML;
}

/**
 * Builds a single issue item.
 *
 * @param issue - Issue to format
 * @returns HTML issue item
 * @private
 */
function buildIssueItem(issue: Issue): string {
  const screenshotInfo = issue.screenshot
    ? `<div style="margin-top: 8px; font-size: 12px; color: #666;"><strong>Evidence:</strong> <code>${escapeHtml(issue.screenshot)}</code></div>`
    : "";

  return `
    <div class="issue-item ${issue.severity}">
      <span class="issue-badge ${issue.severity}">${issue.severity}</span>
      <strong>${escapeHtml(issue.category)}:</strong> ${escapeHtml(issue.description)}
      ${screenshotInfo}
    </div>
  `;
}

/**
 * Builds the actions section.
 *
 * @param report - QA report
 * @returns HTML actions section
 * @private
 */
function buildActionsSection(report: QAReport): string {
  if (report.actions.length === 0) {
    return `
      <section class="actions">
        <h2>Actions Taken</h2>
        <p>No actions recorded.</p>
      </section>
    `;
  }

  const actionsHTML = report.actions
    .map((action) => {
      const statusClass = action.success ? "success" : "failure";
      const details = action.details
        ? `<div style="margin-top: 5px; font-size: 12px; color: #666;">${escapeHtml(action.details)}</div>`
        : "";

      return `
        <li class="action-item ${statusClass}">
          <span class="action-type">${escapeHtml(action.type)}</span>
          <span class="action-timestamp">${new Date(action.timestamp).toLocaleTimeString()}</span>
          ${details}
        </li>
      `;
    })
    .join("");

  return `
    <section class="actions">
      <h2>Actions Taken</h2>
      <ul class="action-timeline">
        ${actionsHTML}
      </ul>
    </section>
  `;
}

/**
 * Converts an image file to a base64 data URI.
 *
 * @param imagePath - Absolute path to the image file
 * @returns Base64 data URI string
 * @private
 */
async function imageToBase64(imagePath: string): Promise<string> {
  try {
    const imageBuffer = await readFile(imagePath);
    const base64 = imageBuffer.toString("base64");

    // Determine MIME type from file extension
    const ext = imagePath.split(".").pop()?.toLowerCase();
    const mimeType =
      ext === "png"
        ? "image/png"
        : ext === "jpg" || ext === "jpeg"
          ? "image/jpeg"
          : "image/png";

    return `data:${mimeType};base64,${base64}`;
  } catch (error) {
    log.warn({ imagePath, error }, "Failed to convert image to base64");
    // Return a placeholder or empty data URI if image can't be read
    return "";
  }
}

/**
 * Builds the evidence section with screenshots and logs.
 *
 * @param report - QA report
 * @param outputPath - Path where HTML will be saved (used to resolve screenshot paths)
 * @returns HTML evidence section
 * @private
 */
async function buildEvidenceSection(
  report: QAReport,
  outputPath: string,
): Promise<string> {
  let screenshotsHTML = "";

  if (report.evidence.screenshots.length > 0) {
    // Get the directory containing the HTML report
    const reportDir = dirname(outputPath);

    // Convert all screenshots to base64 in parallel
    const screenshotPromises = report.evidence.screenshots.map(
      async (path, index) => {
        const filename = path.split("/").pop() || path;

        // Resolve the absolute path to the screenshot
        // Screenshots are typically at ../screenshots/ relative to reports/
        const screenshotPath = join(reportDir, "..", "screenshots", filename);

        // Convert to base64
        const base64DataUri = await imageToBase64(screenshotPath);

        if (!base64DataUri) {
          // If conversion failed, return empty item
          return "";
        }

        return `
          <div class="screenshot-item">
            <img src="${base64DataUri}" alt="Screenshot ${index + 1}" loading="lazy" onclick="openLightbox('${base64DataUri}')" />
            <div class="filename">${escapeHtml(filename)}</div>
          </div>
        `;
      },
    );

    const screenshotItems = await Promise.all(screenshotPromises);
    screenshotsHTML = `
      <h3>Screenshots</h3>
      <div class="screenshot-gallery">
        ${screenshotItems.filter((item) => item).join("")}
      </div>
    `;
  }

  return `
    <section class="evidence">
      <h2>Evidence</h2>
      ${screenshotsHTML}
      <h3>Logs</h3>
      <div class="log-path"><strong>Console Log:</strong> ${escapeHtml(report.evidence.logs.console)}</div>
      <div class="log-path"><strong>Actions Log:</strong> ${escapeHtml(report.evidence.logs.actions)}</div>
      <div class="log-path"><strong>Errors Log:</strong> ${escapeHtml(report.evidence.logs.errors)}</div>
    </section>
  `;
}

/**
 * Builds the progress metrics section showing game progression insights.
 *
 * @param report - QA report
 * @returns HTML progress metrics section
 * @private
 */
function buildProgressMetricsSection(report: QAReport): string {
  if (!report.progressMetrics) {
    return "";
  }

  const metrics = report.progressMetrics;

  return `
    <section class="card">
      <h2>Progress Metrics</h2>
      <div class="metrics-grid">
        <div class="metric-item">
          <div class="metric-label">Unique States Seen</div>
          <div class="metric-value">${metrics.uniqueStates}</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Total Actions</div>
          <div class="metric-value">${metrics.totalActions}</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Successful Actions</div>
          <div class="metric-value">${metrics.successfulActions}</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Input Success Rate</div>
          <div class="metric-value">${metrics.inputSuccessRate.toFixed(1)}%</div>
        </div>
      </div>
    </section>
  `;
}

/**
 * Builds the timing metrics section showing action performance insights.
 *
 * @param report - QA report
 * @returns HTML timing metrics section
 * @private
 */
function buildTimingMetricsSection(report: QAReport): string {
  if (!report.timingMetrics) {
    return "";
  }

  const metrics = report.timingMetrics;

  return `
    <section class="card">
      <h2>Timing Metrics</h2>
      <div class="metrics-grid">
        <div class="metric-item">
          <div class="metric-label">Total Timed Actions</div>
          <div class="metric-value">${metrics.totalTimedActions}</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Average Duration</div>
          <div class="metric-value">${metrics.averageDurationMs}ms</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Min Duration</div>
          <div class="metric-value">${metrics.minDurationMs}ms</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Max Duration</div>
          <div class="metric-value">${metrics.maxDurationMs}ms</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Total Duration</div>
          <div class="metric-value">${metrics.totalDurationMs}ms</div>
        </div>
        <div class="metric-item">
          <div class="metric-label">Slow Actions (&gt;5s)</div>
          <div class="metric-value">${metrics.slowActionsCount}</div>
        </div>
      </div>
    </section>
  `;
}

/**
 * Escapes HTML special characters to prevent XSS.
 *
 * @param unsafe - Unsafe string
 * @returns HTML-safe string
 * @private
 */
function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
